=== timsong-cpp/LWG/xml/lwg-issue.dtd
<!ELEMENT issue (title,section,submitter,date,priority?,(note,p*)?,discussion,(resolution|rationale|duplicate|note|blockquote)*)>
<!ATTLIST issue num CDATA #REQUIRED>
<!ATTLIST issue status CDATA #REQUIRED>
<!ELEMENT title ANY>
<!ELEMENT section (sref+)>
<!ELEMENT submitter (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT priority (#PCDATA)>
<!ELEMENT discussion ANY>
<!ELEMENT resolution ANY>
<!ELEMENT rationale ANY>
<!ELEMENT duplicate (iref)>
<!ELEMENT sref EMPTY>
<!ATTLIST sref ref CDATA #REQUIRED>
<!ELEMENT iref EMPTY>
<!ATTLIST iref ref CDATA #REQUIRED>
<!ELEMENT note ANY>

<!ENTITY % html-inline "tt|code|i|em|b|strong|u|a|sup|sub|br|var|span|dfn|del|ins">
<!ENTITY % html-table "table|thead|tbody|caption|tr|th|td">
<!ENTITY % html-list "ol|ul|li|dl|dt|dd">
<!ENTITY % html-block "p|pre|blockquote|h3|h4|h5|%html-table;|%html-list;">
<!ENTITY % html "%html-inline; | %html-block;">

<!-- HTML elements used in issues -->
<!ELEMENT del ANY>
<!ELEMENT ins ANY>
<!ATTLIST ins style CDATA #IMPLIED>
<!ELEMENT pre ANY>
<!ELEMENT blockquote ANY>
<!ATTLIST blockquote class (note) #IMPLIED> <!-- issue 427 needs this -->
<!ATTLIST blockquote style CDATA #IMPLIED>
<!ELEMENT p ANY>
<!ATTLIST p style CDATA #IMPLIED>
<!ELEMENT h3 ANY>
<!ELEMENT h4 ANY>
<!ELEMENT h5 ANY>
<!ELEMENT ol (li+)>
<!ATTLIST ol style CDATA #IMPLIED>
<!ATTLIST ol start CDATA #IMPLIED>
<!ELEMENT ul (li+)>
<!ELEMENT li ANY>
<!ATTLIST li value CDATA #IMPLIED>
<!ELEMENT i ANY>
<!ELEMENT em ANY>
<!ELEMENT b ANY>
<!ELEMENT strong ANY>
<!ELEMENT u ANY>
<!ELEMENT tt ANY>
<!ELEMENT code ANY>
<!ELEMENT sup ANY>
<!ELEMENT sub ANY>
<!ELEMENT br ANY>
<!ELEMENT a ANY>
<!ATTLIST a href CDATA #IMPLIED>
<!ATTLIST a name CDATA #IMPLIED>
<!ELEMENT table (caption?,((thead?,tbody)|tr+))>
<!ATTLIST table style CDATA #IMPLIED>
<!ATTLIST table border CDATA #IMPLIED>
<!ATTLIST table bordercolor CDATA #IMPLIED>
<!ATTLIST table cellpadding CDATA #IMPLIED>
<!ATTLIST table cellspacing CDATA #IMPLIED>
<!ATTLIST table rules CDATA #IMPLIED>
<!ELEMENT thead ANY>
<!ELEMENT tbody ANY>
<!ELEMENT tr ((th|td)+)>
<!ATTLIST tr style CDATA #IMPLIED>
<!ATTLIST tr align CDATA #IMPLIED>
<!ELEMENT th ANY>
<!ATTLIST th style CDATA #IMPLIED>
<!ATTLIST th colspan CDATA #IMPLIED>
<!ATTLIST th align CDATA #IMPLIED>
<!ELEMENT td ANY>
<!ATTLIST td style CDATA #IMPLIED>
<!ATTLIST td colspan CDATA #IMPLIED>
<!ATTLIST td rowspan CDATA #IMPLIED>
<!ATTLIST td align CDATA #IMPLIED>
<!ATTLIST td valign CDATA #IMPLIED>
<!ELEMENT caption ANY>
<!ELEMENT dl ((dd|dt)+)>
<!ELEMENT dt ANY>
<!ELEMENT dd ANY>
<!ELEMENT var ANY>
<!ELEMENT span ANY>
<!ATTLIST span style CDATA #IMPLIED>
<!ELEMENT dfn ANY>

<!-- MathML elements, simplified DTD version derived from:

     https://www.w3.org/TR/MathML2/appendixa.html
     
     To convert LaTeX to MathML, use e.g.:
     
     https://www.mathtowebonline.com/
     
     Useful MathML introductions:
     
     http://www.xmlmind.com/tutorials/MathML/
     http://rypress.com/tutorials/mathml/advanced-formatting
-->
<!ENTITY % MathMLCharacters "#PCDATA | mglyph">
<!ENTITY % MathExpression           
     "(mi|mn|mo|mtext|ms|mspace|mrow|mfrac|msqrt|mroot|menclose|mstyle|mfenced|
       mtable)*">
<!ENTITY % PresExpression      
     "(mfenced|mi|mo|mn|msup|mtext|ms|mspace|mprescripts|mfrac|msqrt|mroot|mrow|mstyle|
       msub|msup|msubsup|munder|mover|munderover|mmultiscripts|mtable|mtr|mlabeledtr|
       mtd)*">
<!ENTITY % MATHML.NamespaceDecl.attrib "xmlns CDATA #REQUIRED">
<!ENTITY % MATHML.Common.attrib
     "class  CDATA  #IMPLIED
      style  CDATA  #IMPLIED
      id     ID     #IMPLIED
      xref   IDREF  #IMPLIED
      other  CDATA  #IMPLIED">
<!ENTITY % att-bevelled        "bevelled CDATA #IMPLIED">
<!ENTITY % att-display         "display CDATA #IMPLIED">
<!ENTITY % att-numalign        "numalign CDATA #IMPLIED">
<!ENTITY % att-denomalign      "denomalign CDATA #IMPLIED">
<!ENTITY % att-linethickness   "linethickness CDATA #IMPLIED">
<!ENTITY % att-fontsize        "fontsize CDATA #IMPLIED">
<!ENTITY % att-fontweight      "fontweight (normal|bold) #IMPLIED">
<!ENTITY % att-fontstyle       "fontstyle (normal|italic) #IMPLIED">
<!ENTITY % att-fontfamily      "fontfamily CDATA #IMPLIED">
<!ENTITY % att-color           "color CDATA #IMPLIED">
<!ENTITY % att-mathvariant     "mathvariant CDATA #IMPLIED">
<!ENTITY % att-mathsize        "mathsize CDATA #IMPLIED">
<!ENTITY % att-mathcolor       "mathcolor CDATA #IMPLIED">
<!ENTITY % att-mathbackground  "mathbackground CDATA #IMPLIED">
<!ENTITY % att-mode            "mode CDATA #IMPLIED">
<!ENTITY % att-fontinfo        "%att-fontsize; %att-fontweight; %att-fontstyle;
                                %att-fontfamily; %att-color; %att-mathvariant;
                                %att-mathsize; %att-mathcolor; %att-mathbackground;">
<!ENTITY % att-form            "form  (prefix|infix|postfix ) #IMPLIED">
<!ENTITY % att-fence           "fence  (true|false) #IMPLIED">
<!ENTITY % att-separator       "separator (true|false) #IMPLIED">
<!ENTITY % att-lspace          "lspace CDATA #IMPLIED">
<!ENTITY % att-rspace          "rspace CDATA #IMPLIED">
<!ENTITY % att-stretchy        "stretchy (true|false) #IMPLIED">
<!ENTITY % att-symmetric       "symmetric (true|false) #IMPLIED">
<!ENTITY % att-maxsize         "maxsize CDATA #IMPLIED">
<!ENTITY % att-minsize         "minsize CDATA #IMPLIED">
<!ENTITY % att-largeop         "largeop (true|false) #IMPLIED">
<!ENTITY % att-movablelimits   "movablelimits (true|false) #IMPLIED">
<!ENTITY % att-accent          "accent (true|false) #IMPLIED">
<!ENTITY % att-opinfo          "%att-form; %att-fence; %att-separator; %att-lspace; %att-rspace;
                                %att-stretchy; %att-symmetric; %att-maxsize; %att-minsize;
                                %att-largeop; %att-movablelimits; %att-accent;">
<!ENTITY % att-lquote          "lquote CDATA #IMPLIED">
<!ENTITY % att-rquote          "rquote CDATA #IMPLIED">
<!ENTITY % att-linethickness   "linethickness CDATA #IMPLIED">
<!ENTITY % att-scriptlevel     "scriptlevel CDATA #IMPLIED">
<!ENTITY % att-displaystyle    "displaystyle (true|false) #IMPLIED">
<!ENTITY % att-scriptsizemultiplier "scriptsizemultiplier CDATA #IMPLIED">
<!ENTITY % att-scriptminsize   "scriptminsize CDATA #IMPLIED">
<!ENTITY % att-background      "background CDATA #IMPLIED">
<!ENTITY % att-open            "open CDATA #IMPLIED">
<!ENTITY % att-close           "close CDATA #IMPLIED">
<!ENTITY % att-separators      "separators CDATA #IMPLIED">
<!ENTITY % att-subscriptshift  "subscriptshift CDATA #IMPLIED">
<!ENTITY % att-superscriptshift "superscriptshift CDATA #IMPLIED">
<!ENTITY % att-accentunder     "accentunder (true|false) #IMPLIED">
<!ENTITY % att-align           "align CDATA #IMPLIED">
<!ENTITY % att-rowspan         "rowspan CDATA #IMPLIED">
<!ENTITY % att-columnspan      "columnspan CDATA #IMPLIED">
<!ENTITY % att-edge            "edge (left|right) #IMPLIED">
                             
<!ENTITY % twoPresExpression   "%PresExpression;">
<!ENTITY % threePresExpression "%PresExpression;">
<!ENTITY % prscrPresExpression "%PresExpression;">

<!ELEMENT math          (%MathExpression;)>
<!ELEMENT malignmark    EMPTY>
<!ELEMENT mglyph        EMPTY>
<!ELEMENT mrow          (%PresExpression;)>
<!ELEMENT mi            (%MathMLCharacters; | malignmark)*>
<!ELEMENT mn            (%MathMLCharacters; | malignmark)*>
<!ELEMENT mo            (%MathMLCharacters; | malignmark)*>
<!ELEMENT mtext         (%MathMLCharacters; | malignmark)*>
<!ELEMENT ms            (%MathMLCharacters; | malignmark)*>
<!ELEMENT mfenced       (%PresExpression;)>
<!ELEMENT mroot         (%twoPresExpression;)>
<!ELEMENT msub          (%twoPresExpression;)>
<!ELEMENT msup          (%twoPresExpression;)>
<!ELEMENT msubsup       (%threePresExpression;)>
<!ELEMENT mmultiscripts (%prscrPresExpression;)>
<!ELEMENT munder        (%twoPresExpression;)>
<!ELEMENT munderover    (%threePresExpression;)>
<!ELEMENT mover         (%twoPresExpression;)>
<!ELEMENT mfrac         (%twoPresExpression;)>
<!ELEMENT msqrt         (%PresExpression;)>
<!ELEMENT mstyle        (%PresExpression;)>

<!ATTLIST math          %att-mode; %att-display; %MATHML.NamespaceDecl.attrib;>
<!ATTLIST mglyph        %att-alt; %att-fontfamily; %att-index;>
<!ATTLIST mrow          %MATHML.Common.attrib;>
<!ATTLIST mi            %MATHML.Common.attrib; %att-fontinfo;>
<!ATTLIST mo            %MATHML.Common.attrib; %att-fontinfo; %att-opinfo;>
<!ATTLIST mn            %MATHML.Common.attrib; %att-fontinfo;>
<!ATTLIST mtext         %MATHML.Common.attrib; %att-fontinfo;>
<!ATTLIST ms            %MATHML.Common.attrib; %att-fontinfo; %att-lquote; %att-rquote;>
<!ATTLIST mfenced       %MATHML.Common.attrib; %att-open; %att-close; %att-separators;>
<!ATTLIST mfrac         %MATHML.Common.attrib; %att-bevelled; %att-numalign; %att-denomalign; %att-linethickness;>
<!ATTLIST msqrt         %MATHML.Common.attrib;>
<!ATTLIST mroot         %MATHML.Common.attrib;>
<!ATTLIST msub          %MATHML.Common.attrib; %att-subscriptshift;>
<!ATTLIST msup          %MATHML.Common.attrib; %att-superscriptshift;>
<!ATTLIST msubsup       %MATHML.Common.attrib; %att-subscriptshift; %att-superscriptshift;>
<!ATTLIST munder        %MATHML.Common.attrib; %att-accentunder;>
<!ATTLIST mover         %MATHML.Common.attrib; %att-accent;>
<!ATTLIST munderover    %MATHML.Common.attrib; %att-accent; %att-accentunder;>
<!ATTLIST mmultiscripts %MATHML.Common.attrib; %att-subscriptshift; %att-superscriptshift;>
<!ATTLIST mstyle        %MATHML.Common.attrib; %att-fontinfo; %att-opinfo; %att-lquote;
                        %att-rquote; %att-linethickness; %att-scriptlevel; %att-scriptsizemultiplier;
                        %att-scriptminsize; %att-background; %att-open; %att-close;
                        %att-separators; %att-subscriptshift; %att-superscriptshift;
                        %att-accentunder; %att-tableinfo; %att-rowspan; %att-columnspan;
                        %att-edge; %att-selection; %att-bevelled; %att-height; %att-depth;>

<!-- the common HTML entities for special characters -->
<!ENTITY Aacute     "&#xC1;">
<!ENTITY aacute     "&#xE1;">
<!ENTITY Acirc      "&#xC2;">
<!ENTITY acirc      "&#xE2;">
<!ENTITY Agrave     "&#xC0;">
<!ENTITY agrave     "&#xE0;">
<!ENTITY Atilde     "&#xC3;">
<!ENTITY atilde     "&#xE3;">
<!ENTITY Auml       "&#xC4;">
<!ENTITY auml       "&#xE4;">
<!ENTITY Ccedil     "&#xC7;">
<!ENTITY ccedil     "&#xE7;">
<!ENTITY deg        "&#xB0;">
<!ENTITY Delta      "&#x394;">
<!ENTITY delta      "&#x3B4;">
<!ENTITY divide     "&#xF7;">
<!ENTITY Eacute     "&#xC9;">
<!ENTITY eacute     "&#xE9;">
<!ENTITY Ecirc      "&#xCA;">
<!ENTITY ecirc      "&#xEA;">
<!ENTITY Egrave     "&#xC8;">
<!ENTITY egrave     "&#xE8;">
<!ENTITY empty      "&#x2205;">
<!ENTITY epsilon    "&#x3B5;">
<!ENTITY Euml       "&#xCB;">
<!ENTITY euml       "&#xEB;">
<!ENTITY exist      "&#x2203;">
<!ENTITY forall     "&#x2200;">
<!ENTITY frasl      "&#x2044;">
<!ENTITY ge         "&#x2265;">
<!ENTITY hArr       "&#x21D4;">
<!ENTITY harr       "&#x2194;">
<!ENTITY hellip     "&#x2026;">
<!ENTITY Iacute     "&#xCD;">
<!ENTITY iacute     "&#xED;">
<!ENTITY Icirc      "&#xCE;">
<!ENTITY icirc      "&#xEE;">
<!ENTITY Igrave     "&#xCC;">
<!ENTITY igrave     "&#xEC;">
<!ENTITY isin       "&#x2208;">
<!ENTITY Iuml       "&#xCF;">
<!ENTITY iuml       "&#xEF;">
<!ENTITY lArr       "&#x21D0;">
<!ENTITY larr       "&#x2190;">
<!ENTITY ldquo      "&#x201C;">
<!ENTITY le         "&#x2264;">
<!ENTITY lfloor     "&#x230A;">
<!ENTITY mdash      "&#x2014;">
<!ENTITY micro      "&#xB5;">
<!ENTITY middot     "&#xB7;">
<!ENTITY mu     	"&#x03BC;">
<!ENTITY Nacute     "&#x8f;">
<!ENTITY nacute     "&#x90;">
<!ENTITY nbsp       "&#xA0;">
<!ENTITY ndash      "&#x2013;">
<!ENTITY ne         "&#x2260;">
<!ENTITY ni         "&#x220B;">
<!ENTITY notin      "&#x2209;">
<!ENTITY nsub       "&#x2284;">
<!ENTITY Ntilde     "&#xD1;">
<!ENTITY ntilde     "&#xF1;">
<!ENTITY Oacute     "&#xD3;">
<!ENTITY oacute     "&#xF3;">
<!ENTITY Ocirc      "&#xD4;">
<!ENTITY ocirc      "&#xF4;">
<!ENTITY Omicron    "&#x39F;">   <!-- Better use &#x1d4aa; for big-O notation ('MATHEMATICAL SCRIPT CAPITAL O') -->
<!ENTITY Otilde     "&#xD5;">
<!ENTITY otilde     "&#xF5;">
<!ENTITY Ouml       "&#xD6;">
<!ENTITY ouml       "&#xF6;">
<!ENTITY para       "&#xB6;">
<!ENTITY phi        "&#x3C6;">
<!ENTITY pi         "&#x3C0;">
<!ENTITY plusmn     "&#xB1;">
<!ENTITY rArr       "&#x21D2;">
<!ENTITY rarr       "&#x2192;">
<!ENTITY rdquo      "&#x201D;">
<!ENTITY rfloor     "&#x230B;">
<!ENTITY rho        "&#x3C1;">
<!ENTITY rsquo      "&#x2019;">
<!ENTITY Scaron     "&#x160;">
<!ENTITY scaron     "&#x161;">
<!ENTITY sect       "&#xA7;">
<!ENTITY sigma      "&#x3C3;">
<!ENTITY sub        "&#x2282;">
<!ENTITY sube       "&#x2286;">
<!ENTITY sum        "&#x2211;">
<!ENTITY sup        "&#x2283;">
<!ENTITY supe       "&#x2287;">
<!ENTITY szlig      "&#xDF;">
<!ENTITY Theta      "&#x398;">
<!ENTITY times      "&#xD7;">
<!ENTITY Uacute     "&#xDA;">
<!ENTITY uacute     "&#xFA;">
<!ENTITY Ucirc      "&#xDB;">
<!ENTITY ucirc      "&#xFB;">
<!ENTITY Ugrave     "&#xD9;">
<!ENTITY ugrave     "&#xF9;">
<!ENTITY Uuml       "&#xDC;">
<!ENTITY uuml       "&#xFC;">
<!ENTITY yacute     "&#xFD;">
<!ENTITY yuml       "&#xFF;">
<!ENTITY zcaron     "&#x17D;">

=== timsong-cpp/LWG/xml/issue3479.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3479" status="New">
<title><tt><i>semiregular-box</i></tt> mishandles self-assignment</title>
<section><sref ref="[range.semi.wrap]"/></section>
<submitter>Casey Carter</submitter>
<date>25 Aug 2020</date>
<priority>99</priority>

<discussion>
<p>
The exposition-only wrapper type <tt><i>semiregular-box</i></tt> &mdash; specified in <sref ref="[range.semi.wrap]"/> 
&mdash; layers behaviors onto <tt>std::optional</tt> so <tt><i>semiregular-box</i>&lt;T&gt;</tt> is 
semiregular even when <tt>T</tt> is only copy constructible. It provides copy and move assignment 
operators when <tt>optional&lt;T&gt;</tt>'s are deleted:
</p>
<blockquote><p>
<ol style="list-style-type: none">
<li><p>(1.1) &mdash; [&hellip;]</p></li>
<li><p>(1.2) &mdash; [&hellip;]</p></li>
<li><p>(1.3) &mdash; If <tt>assignable_from&lt;T&amp;, const T&amp;&gt;</tt> 
is not modeled, the copy assignment operator is equivalent to:</p>
<pre>
<i>semiregular-box</i>&amp; operator=(const <i>semiregular-box</i>&amp; that)
  noexcept(is_nothrow_copy_constructible_v&lt;T&gt;)
{
  if (that) emplace(*that);
  else reset();
  return *this;
}
</pre>
</li>
<li><p>(1.4) &mdash; If <tt>assignable_from&lt;T&amp;, T&gt;</tt> 
is not modeled, the move assignment operator is equivalent to:</p>
<pre>
<i>semiregular-box</i>&amp; operator=(<i>semiregular-box</i>&amp;&amp; that)
  noexcept(is_nothrow_move_constructible_v&lt;T&gt;)
{
  if (that) emplace(std::move(*that));
  else reset();
  return *this;
}
</pre>
</li>
</ol>
</p></blockquote>
<p>
How do these assignment operators handle self-assignment? When <tt>*this</tt> is empty, <tt>that</tt> 
will test as <tt>false</tt> and <tt>reset()</tt> has no effect, so the result state of the object is 
the same. No problems so far. When <tt>*this</tt> isn't empty, <tt>that</tt> will test as <tt>true</tt>, 
and we evaluate <tt>optional::emplace(**this)</tt> (resp. <tt>optional::emplace(std::move(**this)))</tt>. 
This outcome is not as pretty: <tt>emplace</tt> is specified in <sref ref="[optional.assign]"/>/30: 
"<i>Effects:</i> Calls <tt>*this = nullopt</tt>. Then initializes the contained value as if 
direct-non-list-initializing an object of type <tt>T</tt> with the arguments 
<tt>std::forward&lt;Args&gt;(args)...</tt>." When the sole argument is an lvalue (resp. xvalue) of type 
<tt>T</tt> that denotes the <tt>optional</tt>'s stored value, <tt>emplace</tt> will destroy that 
stored value and then try to copy/move construct a new object at the same address from the dead object 
that used to live there resulting in undefined behavior. Mandatory undefined behavior does <em>not</em> 
meet the semantic requirements for the <tt>copyable</tt> or <tt>movable</tt> concepts, we should do better.
</p>
</discussion>

<resolution>
<p>
This wording is relative to <a href="https://wg21.link/n4861">N4861</a>.
</p>

<ol>
<li><p>Modify <sref ref="[range.semi.wrap]"/> as indicated:</p>

<blockquote>
<p>
-1- Many types in this subclause are specified in terms of an exposition-only class template 
<tt><i>semiregular-box</i></tt>. <tt><i>semiregular-box</i>&lt;T&gt;</tt> behaves exactly like 
<tt>optional&lt;T&gt;</tt> with the following differences:
</p>
<ol style="list-style-type: none">
<li><p>(1.1) &mdash; [&hellip;]</p></li>
<li><p>(1.2) &mdash; [&hellip;]</p></li>
<li><p>(1.3) &mdash; If <tt>assignable_from&lt;T&amp;, const T&amp;&gt;</tt> 
is not modeled, the copy assignment operator is equivalent to:</p>
<pre>
<i>semiregular-box</i>&amp; operator=(const <i>semiregular-box</i>&amp; that)
  noexcept(is_nothrow_copy_constructible_v&lt;T&gt;)
{
  <ins>if (this != addressof(that)) {</ins>
    if (that) emplace(*that);
    else reset();
  <ins>}</ins>
  return *this;
}
</pre>
</li>
<li><p>(1.4) &mdash; If <tt>assignable_from&lt;T&amp;, T&gt;</tt> 
is not modeled, the move assignment operator is equivalent to:</p>
<pre>
<i>semiregular-box</i>&amp; operator=(<i>semiregular-box</i>&amp;&amp; that)
  noexcept(is_nothrow_move_constructible_v&lt;T&gt;)
{
  <ins>reset();</ins>
  if (that) emplace(std::move(*that));
  <del>else reset();</del>
  return *this;
}
</pre>
</li>
</ol>
</blockquote>
</li>

</ol>
</resolution>

</issue>

=== timsong-cpp/LWG/xml/issue2918.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="2918" status="Tentatively Resolved">
<title>Possible need for extra storage in <tt>inner_product</tt></title>
<section><sref ref="[inner.product]"/></section>
<submitter>United States</submitter>
<date>3 Feb 2017</date>
<priority>99</priority>

<discussion>
<b>Addresses US 161</b>

<p>There is a surprising sequential operation applying <tt>BinaryOp1</tt> in <tt>inner_product</tt> that may, for example, 
require additional storage for the parallel algorithms to enable effective distribution of work, and is likely to be a 
performance bottleneck. <tt><i>GENERALIZED_SUM</i></tt> is probably intended here for the parallel version of the algorithm, 
with the corresponding strengthening on constraints on <tt>BinaryOp1</tt> to allow arbitrary order of evaluation.</p>
<p>Proposed change: For the overloads taking an execution policy, copy the current specification, but replace algorithm in 
<i>Effects</i> with</p>
<blockquote><pre>
<i>GENERALIZED_SUM</i>(plus&lt;&gt;(), init, multiplies&lt;&gt;(*i1, *i2), ...)
<i>GENERALIZED_SUM</i>(binary_op1, init, binary_op2(*i1, *i2), ...)
</pre></blockquote>

<note>2017-03-12, post-Kona</note>
<p>Resolved by P0623R0.</p>
</discussion>

<resolution>
<p>
</p>
</resolution>

</issue>

=== timsong-cpp/LWG/xml/issue2679.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="2679" status="C++17">
<title>Inconsistent Use of Effects and Equivalent To</title>
<section><sref ref="[structure.specifications]"/></section>
<submitter>Dawn Perchik</submitter>
<date>14 Apr 2016</date>
<priority>3</priority>

<discussion>
<ul>
<li><p>
Some <i>Effects</i>: were intended to include the "Equivalent to" phrasing where no or different words were used.  
See examples in <tt>std::filesystem</tt> and throughout the library.
</p></li>
<li><p>
The wording in [structure.specifications]/4 is incorrect and <i>Effects</i>: throughout the library which use 
(or were intended to use) the "Equivalent to" phrasing need to be checked to make sure they fit the intended wording.
</p></li>
</ul>

<note>2016-04, Issues Telecon</note>
<p>
The PR is fine; but bullet #1 in the report really should have a list of places to change.
<p/>
Jonathan checked throughout the library for bullet #2 and found two problems in [string.access], 
which have been added to the PR.
</p>

<note>2016-08-03 Chicago</note>
<p>Fri PM: Move to Tentatively Ready</p>
</discussion>

<resolution>
<ol>
<li>
<p>Change [structure.specifications]/4 as indicated:</p>

<blockquote>
<p>
"[&hellip;] if <tt>F</tt> has no <i>Returns</i>: element, a non-<tt>void</tt> return from <tt>F</tt> is specified by the 
<del>Returns: elements</del><ins>return statements</ins> in the code sequence."
</p>
</blockquote>
</li>

<li><p>Add two <tt>return</tt> keywords to [string.access]:</p>

<blockquote>
<pre>
const charT&amp; front() const;
charT&amp; front();
</pre>
<blockquote>
<p>-7- <i>Requires:</i> <code>!empty()</code>.</p>
<p>-8- <i>Effects:</i> Equivalent to <code><ins>return </ins>operator[](0)</code>.</p>
</blockquote>

<pre>
const charT&amp; back() const;
charT&amp; back();
</pre>
<blockquote>
<p>-9- <i>Requires:</i> <code>!empty()</code>.</p>
<p>-10- <i>Effects:</i> Equivalent to <code><ins>return </ins>operator[](size() - 1)</code>.</p>
</blockquote>
</blockquote>
</li>
</ol>
</resolution>

</issue>

=== timsong-cpp/LWG/xml/issue3732.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3732" status="Tentatively Ready">
<title><tt>prepend_range</tt> and <tt>append_range</tt> can't be amortized constant time</title>
<section><sref ref="[sequence.reqmts]"/></section>
<submitter>Tim Song</submitter>
<date>06 Jul 2022</date>
<priority>99</priority>

<discussion>
<p>
<sref ref="[sequence.reqmts]"/>/69 says "An implementation shall implement them so as to take amortized constant time." 
followed by a list of operations that includes the newly added <tt>append_range</tt> and <tt>prepend_range</tt>. 
Obviously these operations cannot be implemented in amortized constant time.
<p/>
Because the actual complexity of these operations are already specified in the concrete container specification, 
we can just exclude them here.
</p>

<note>2022-08-23; Reflector poll</note>
<p>
Set status to Tentatively Ready after six votes in favour during reflector poll.
</p>

</discussion>

<resolution>
<p>
This wording is relative to <paper num="N4910"/>.
</p>

<ol>

<li><p>Modify <sref ref="[sequence.reqmts]"/> as indicated:</p>

<blockquote>
<p>
-69- The following operations are provided for some types of sequence containers but not others. <del>An implementation
shall implement them</del><ins>Operations other than <tt>prepend_range</tt> and <tt>append_range</tt> are implemented</ins> 
so as to take amortized constant time.
</p>
</blockquote>
</li>


</ol>
</resolution>

</issue>

=== timsong-cpp/LWG/xml/issue3064.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3064" status="New">
<title>How do uninitialized memory algorithms obtain pointer without undefined behavior?</title>
<section><sref ref="[specialized.algorithms]"/></section>
<submitter>Alisdair Meredith</submitter>
<date>12 Feb 2018</date>
<priority>3</priority>

<discussion>
<p>
A typical specification of the algorithms for initializing raw memory in <tt>&lt;memory&gt;</tt> looks like:
</p>
<blockquote>
<p>
<i>Effects:</i> Equivalent to:
</p>
<blockquote><pre>
for (; first != last; ++first)
  ::new (static_cast&lt;void*&gt;(addressof(*first)))
    typename iterator_traits&lt;ForwardIterator&gt;::value_type;
</pre></blockquote>
</blockquote>
<p>
However, this hides a nasty question:
<p/>
How do we bind a reference to an uninitialized object when dereferencing our iterator,
so that <tt>static_cast&lt;void*&gt;(addressof(*first))</tt> does not trigger undefined behavior on
the call to <tt>*first</tt>?
<p/>
When pointers are the only iterators we cared about, we could simply cast the iterator
value to <tt>void*</tt> without dereferencing. I don't see how to implement this spec safely
without introducing another customization point for iterators that performs the same
function as casting a pointer to <tt>void*</tt> in order to get the address of the element.
</p>

<note>2018-02-20, Priority set to 3 after mailing list discussion</note>
</discussion>

<resolution>
</resolution>

</issue>

=== timsong-cpp/LWG/xml/issue3708.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3708" status="C++23">
<title><tt>take_while_view::<i>sentinel</i></tt>'s conversion constructor should move</title>
<section><sref ref="[range.take.while.sentinel]"/></section>
<submitter>Hewill Kang</submitter>
<date>03 Jun 2022</date>
<priority>99</priority>

<discussion>
<p>
The conversion constructor of <tt>take_while_view::<i>sentinel</i></tt> requires 
<tt>sentinel_t&lt;V&gt;</tt> must satisfy <tt>convertible_to&lt;sentinel_t&lt;<i>Base</i>&gt;&gt;</tt>, 
which indicates that the rvalue reference of <tt>sentinel_t&lt;V&gt;</tt> can be converted to 
<tt>sentinel_t&lt;<i>Base</i>&gt;</tt>, but in the <i>Effects</i> element, we assign the lvalue 
<tt>s.<i>end_</i></tt> to <tt><i>end_</i></tt>.
</p>

<note>2022-06-21; Reflector poll</note>
<p>
Set status to Tentatively Ready after seven votes in favour during reflector poll.
</p>

<note>2022-07-15; LWG telecon: move to Ready</note>

<note>2022-07-25 Approved at July 2022 virtual plenary. Status changed: Ready &rarr; WP.</note>
</discussion>

<resolution>
<p>
This wording is relative to <paper num="N4910"/>.
</p>

<ol>
<li><p>Modify <sref ref="[range.take.while.sentinel]"/> as indicated:</p>

<blockquote>
<pre>
constexpr <i>sentinel</i>(<i>sentinel</i>&lt;!Const&gt; s)
  requires Const &amp;&amp; convertible_to&lt;sentinel_t&lt;V&gt;, sentinel_t&lt;<i>Base</i>&gt;&gt;;
</pre>
<blockquote>
<p>
-2- <i>Effects:</i> Initializes <tt><i>end_</i></tt> with <tt><ins>std::move(</ins>s.<i>end_</i><ins>)</ins></tt> and <tt>pred_</tt> with <tt>s.<i>pred_</i></tt>.
</p>
</blockquote>
</blockquote>
</li>

</ol>
</resolution>

</issue>
