=== timsong-cpp/LWG/xml/lwg-issue.dtd
<!ELEMENT issue (title,section,submitter,date,priority?,(note,p*)?,discussion,(resolution|rationale|duplicate|note|blockquote)*)>
<!ATTLIST issue num CDATA #REQUIRED>
<!ATTLIST issue status CDATA #REQUIRED>
<!ELEMENT title ANY>
<!ELEMENT section (sref+)>
<!ELEMENT submitter (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT priority (#PCDATA)>
<!ELEMENT discussion ANY>
<!ELEMENT resolution ANY>
<!ELEMENT rationale ANY>
<!ELEMENT duplicate (iref)>
<!ELEMENT sref EMPTY>
<!ATTLIST sref ref CDATA #REQUIRED>
<!ELEMENT iref EMPTY>
<!ATTLIST iref ref CDATA #REQUIRED>
<!ELEMENT note ANY>

<!ENTITY % html-inline "tt|code|i|em|b|strong|u|a|sup|sub|br|var|span|dfn|del|ins">
<!ENTITY % html-table "table|thead|tbody|caption|tr|th|td">
<!ENTITY % html-list "ol|ul|li|dl|dt|dd">
<!ENTITY % html-block "p|pre|blockquote|h3|h4|h5|%html-table;|%html-list;">
<!ENTITY % html "%html-inline; | %html-block;">

<!-- HTML elements used in issues -->
<!ELEMENT del ANY>
<!ELEMENT ins ANY>
<!ATTLIST ins style CDATA #IMPLIED>
<!ELEMENT pre ANY>
<!ELEMENT blockquote ANY>
<!ATTLIST blockquote class (note) #IMPLIED> <!-- issue 427 needs this -->
<!ATTLIST blockquote style CDATA #IMPLIED>
<!ELEMENT p ANY>
<!ATTLIST p style CDATA #IMPLIED>
<!ELEMENT h3 ANY>
<!ELEMENT h4 ANY>
<!ELEMENT h5 ANY>
<!ELEMENT ol (li+)>
<!ATTLIST ol style CDATA #IMPLIED>
<!ATTLIST ol start CDATA #IMPLIED>
<!ELEMENT ul (li+)>
<!ELEMENT li ANY>
<!ATTLIST li value CDATA #IMPLIED>
<!ELEMENT i ANY>
<!ELEMENT em ANY>
<!ELEMENT b ANY>
<!ELEMENT strong ANY>
<!ELEMENT u ANY>
<!ELEMENT tt ANY>
<!ELEMENT code ANY>
<!ELEMENT sup ANY>
<!ELEMENT sub ANY>
<!ELEMENT br ANY>
<!ELEMENT a ANY>
<!ATTLIST a href CDATA #IMPLIED>
<!ATTLIST a name CDATA #IMPLIED>
<!ELEMENT table (caption?,((thead?,tbody)|tr+))>
<!ATTLIST table style CDATA #IMPLIED>
<!ATTLIST table border CDATA #IMPLIED>
<!ATTLIST table bordercolor CDATA #IMPLIED>
<!ATTLIST table cellpadding CDATA #IMPLIED>
<!ATTLIST table cellspacing CDATA #IMPLIED>
<!ATTLIST table rules CDATA #IMPLIED>
<!ELEMENT thead ANY>
<!ELEMENT tbody ANY>
<!ELEMENT tr ((th|td)+)>
<!ATTLIST tr style CDATA #IMPLIED>
<!ATTLIST tr align CDATA #IMPLIED>
<!ELEMENT th ANY>
<!ATTLIST th style CDATA #IMPLIED>
<!ATTLIST th colspan CDATA #IMPLIED>
<!ATTLIST th align CDATA #IMPLIED>
<!ELEMENT td ANY>
<!ATTLIST td style CDATA #IMPLIED>
<!ATTLIST td colspan CDATA #IMPLIED>
<!ATTLIST td rowspan CDATA #IMPLIED>
<!ATTLIST td align CDATA #IMPLIED>
<!ATTLIST td valign CDATA #IMPLIED>
<!ELEMENT caption ANY>
<!ELEMENT dl ((dd|dt)+)>
<!ELEMENT dt ANY>
<!ELEMENT dd ANY>
<!ELEMENT var ANY>
<!ELEMENT span ANY>
<!ATTLIST span style CDATA #IMPLIED>
<!ELEMENT dfn ANY>

<!-- MathML elements, simplified DTD version derived from:

     https://www.w3.org/TR/MathML2/appendixa.html
     
     To convert LaTeX to MathML, use e.g.:
     
     https://www.mathtowebonline.com/
     
     Useful MathML introductions:
     
     http://www.xmlmind.com/tutorials/MathML/
     http://rypress.com/tutorials/mathml/advanced-formatting
-->
<!ENTITY % MathMLCharacters "#PCDATA | mglyph">
<!ENTITY % MathExpression           
     "(mi|mn|mo|mtext|ms|mspace|mrow|mfrac|msqrt|mroot|menclose|mstyle|mfenced|
       mtable)*">
<!ENTITY % PresExpression      
     "(mfenced|mi|mo|mn|msup|mtext|ms|mspace|mprescripts|mfrac|msqrt|mroot|mrow|mstyle|
       msub|msup|msubsup|munder|mover|munderover|mmultiscripts|mtable|mtr|mlabeledtr|
       mtd)*">
<!ENTITY % MATHML.NamespaceDecl.attrib "xmlns CDATA #REQUIRED">
<!ENTITY % MATHML.Common.attrib
     "class  CDATA  #IMPLIED
      style  CDATA  #IMPLIED
      id     ID     #IMPLIED
      xref   IDREF  #IMPLIED
      other  CDATA  #IMPLIED">
<!ENTITY % att-bevelled        "bevelled CDATA #IMPLIED">
<!ENTITY % att-display         "display CDATA #IMPLIED">
<!ENTITY % att-numalign        "numalign CDATA #IMPLIED">
<!ENTITY % att-denomalign      "denomalign CDATA #IMPLIED">
<!ENTITY % att-linethickness   "linethickness CDATA #IMPLIED">
<!ENTITY % att-fontsize        "fontsize CDATA #IMPLIED">
<!ENTITY % att-fontweight      "fontweight (normal|bold) #IMPLIED">
<!ENTITY % att-fontstyle       "fontstyle (normal|italic) #IMPLIED">
<!ENTITY % att-fontfamily      "fontfamily CDATA #IMPLIED">
<!ENTITY % att-color           "color CDATA #IMPLIED">
<!ENTITY % att-mathvariant     "mathvariant CDATA #IMPLIED">
<!ENTITY % att-mathsize        "mathsize CDATA #IMPLIED">
<!ENTITY % att-mathcolor       "mathcolor CDATA #IMPLIED">
<!ENTITY % att-mathbackground  "mathbackground CDATA #IMPLIED">
<!ENTITY % att-mode            "mode CDATA #IMPLIED">
<!ENTITY % att-fontinfo        "%att-fontsize; %att-fontweight; %att-fontstyle;
                                %att-fontfamily; %att-color; %att-mathvariant;
                                %att-mathsize; %att-mathcolor; %att-mathbackground;">
<!ENTITY % att-form            "form  (prefix|infix|postfix ) #IMPLIED">
<!ENTITY % att-fence           "fence  (true|false) #IMPLIED">
<!ENTITY % att-separator       "separator (true|false) #IMPLIED">
<!ENTITY % att-lspace          "lspace CDATA #IMPLIED">
<!ENTITY % att-rspace          "rspace CDATA #IMPLIED">
<!ENTITY % att-stretchy        "stretchy (true|false) #IMPLIED">
<!ENTITY % att-symmetric       "symmetric (true|false) #IMPLIED">
<!ENTITY % att-maxsize         "maxsize CDATA #IMPLIED">
<!ENTITY % att-minsize         "minsize CDATA #IMPLIED">
<!ENTITY % att-largeop         "largeop (true|false) #IMPLIED">
<!ENTITY % att-movablelimits   "movablelimits (true|false) #IMPLIED">
<!ENTITY % att-accent          "accent (true|false) #IMPLIED">
<!ENTITY % att-opinfo          "%att-form; %att-fence; %att-separator; %att-lspace; %att-rspace;
                                %att-stretchy; %att-symmetric; %att-maxsize; %att-minsize;
                                %att-largeop; %att-movablelimits; %att-accent;">
<!ENTITY % att-lquote          "lquote CDATA #IMPLIED">
<!ENTITY % att-rquote          "rquote CDATA #IMPLIED">
<!ENTITY % att-linethickness   "linethickness CDATA #IMPLIED">
<!ENTITY % att-scriptlevel     "scriptlevel CDATA #IMPLIED">
<!ENTITY % att-displaystyle    "displaystyle (true|false) #IMPLIED">
<!ENTITY % att-scriptsizemultiplier "scriptsizemultiplier CDATA #IMPLIED">
<!ENTITY % att-scriptminsize   "scriptminsize CDATA #IMPLIED">
<!ENTITY % att-background      "background CDATA #IMPLIED">
<!ENTITY % att-open            "open CDATA #IMPLIED">
<!ENTITY % att-close           "close CDATA #IMPLIED">
<!ENTITY % att-separators      "separators CDATA #IMPLIED">
<!ENTITY % att-subscriptshift  "subscriptshift CDATA #IMPLIED">
<!ENTITY % att-superscriptshift "superscriptshift CDATA #IMPLIED">
<!ENTITY % att-accentunder     "accentunder (true|false) #IMPLIED">
<!ENTITY % att-align           "align CDATA #IMPLIED">
<!ENTITY % att-rowspan         "rowspan CDATA #IMPLIED">
<!ENTITY % att-columnspan      "columnspan CDATA #IMPLIED">
<!ENTITY % att-edge            "edge (left|right) #IMPLIED">
                             
<!ENTITY % twoPresExpression   "%PresExpression;">
<!ENTITY % threePresExpression "%PresExpression;">
<!ENTITY % prscrPresExpression "%PresExpression;">

<!ELEMENT math          (%MathExpression;)>
<!ELEMENT malignmark    EMPTY>
<!ELEMENT mglyph        EMPTY>
<!ELEMENT mrow          (%PresExpression;)>
<!ELEMENT mi            (%MathMLCharacters; | malignmark)*>
<!ELEMENT mn            (%MathMLCharacters; | malignmark)*>
<!ELEMENT mo            (%MathMLCharacters; | malignmark)*>
<!ELEMENT mtext         (%MathMLCharacters; | malignmark)*>
<!ELEMENT ms            (%MathMLCharacters; | malignmark)*>
<!ELEMENT mfenced       (%PresExpression;)>
<!ELEMENT mroot         (%twoPresExpression;)>
<!ELEMENT msub          (%twoPresExpression;)>
<!ELEMENT msup          (%twoPresExpression;)>
<!ELEMENT msubsup       (%threePresExpression;)>
<!ELEMENT mmultiscripts (%prscrPresExpression;)>
<!ELEMENT munder        (%twoPresExpression;)>
<!ELEMENT munderover    (%threePresExpression;)>
<!ELEMENT mover         (%twoPresExpression;)>
<!ELEMENT mfrac         (%twoPresExpression;)>
<!ELEMENT msqrt         (%PresExpression;)>
<!ELEMENT mstyle        (%PresExpression;)>

<!ATTLIST math          %att-mode; %att-display; %MATHML.NamespaceDecl.attrib;>
<!ATTLIST mglyph        %att-alt; %att-fontfamily; %att-index;>
<!ATTLIST mrow          %MATHML.Common.attrib;>
<!ATTLIST mi            %MATHML.Common.attrib; %att-fontinfo;>
<!ATTLIST mo            %MATHML.Common.attrib; %att-fontinfo; %att-opinfo;>
<!ATTLIST mn            %MATHML.Common.attrib; %att-fontinfo;>
<!ATTLIST mtext         %MATHML.Common.attrib; %att-fontinfo;>
<!ATTLIST ms            %MATHML.Common.attrib; %att-fontinfo; %att-lquote; %att-rquote;>
<!ATTLIST mfenced       %MATHML.Common.attrib; %att-open; %att-close; %att-separators;>
<!ATTLIST mfrac         %MATHML.Common.attrib; %att-bevelled; %att-numalign; %att-denomalign; %att-linethickness;>
<!ATTLIST msqrt         %MATHML.Common.attrib;>
<!ATTLIST mroot         %MATHML.Common.attrib;>
<!ATTLIST msub          %MATHML.Common.attrib; %att-subscriptshift;>
<!ATTLIST msup          %MATHML.Common.attrib; %att-superscriptshift;>
<!ATTLIST msubsup       %MATHML.Common.attrib; %att-subscriptshift; %att-superscriptshift;>
<!ATTLIST munder        %MATHML.Common.attrib; %att-accentunder;>
<!ATTLIST mover         %MATHML.Common.attrib; %att-accent;>
<!ATTLIST munderover    %MATHML.Common.attrib; %att-accent; %att-accentunder;>
<!ATTLIST mmultiscripts %MATHML.Common.attrib; %att-subscriptshift; %att-superscriptshift;>
<!ATTLIST mstyle        %MATHML.Common.attrib; %att-fontinfo; %att-opinfo; %att-lquote;
                        %att-rquote; %att-linethickness; %att-scriptlevel; %att-scriptsizemultiplier;
                        %att-scriptminsize; %att-background; %att-open; %att-close;
                        %att-separators; %att-subscriptshift; %att-superscriptshift;
                        %att-accentunder; %att-tableinfo; %att-rowspan; %att-columnspan;
                        %att-edge; %att-selection; %att-bevelled; %att-height; %att-depth;>

<!-- the common HTML entities for special characters -->
<!ENTITY Aacute     "&#xC1;">
<!ENTITY aacute     "&#xE1;">
<!ENTITY Acirc      "&#xC2;">
<!ENTITY acirc      "&#xE2;">
<!ENTITY Agrave     "&#xC0;">
<!ENTITY agrave     "&#xE0;">
<!ENTITY Atilde     "&#xC3;">
<!ENTITY atilde     "&#xE3;">
<!ENTITY Auml       "&#xC4;">
<!ENTITY auml       "&#xE4;">
<!ENTITY Ccedil     "&#xC7;">
<!ENTITY ccedil     "&#xE7;">
<!ENTITY deg        "&#xB0;">
<!ENTITY Delta      "&#x394;">
<!ENTITY delta      "&#x3B4;">
<!ENTITY divide     "&#xF7;">
<!ENTITY Eacute     "&#xC9;">
<!ENTITY eacute     "&#xE9;">
<!ENTITY Ecirc      "&#xCA;">
<!ENTITY ecirc      "&#xEA;">
<!ENTITY Egrave     "&#xC8;">
<!ENTITY egrave     "&#xE8;">
<!ENTITY empty      "&#x2205;">
<!ENTITY epsilon    "&#x3B5;">
<!ENTITY Euml       "&#xCB;">
<!ENTITY euml       "&#xEB;">
<!ENTITY exist      "&#x2203;">
<!ENTITY forall     "&#x2200;">
<!ENTITY frasl      "&#x2044;">
<!ENTITY ge         "&#x2265;">
<!ENTITY hArr       "&#x21D4;">
<!ENTITY harr       "&#x2194;">
<!ENTITY hellip     "&#x2026;">
<!ENTITY Iacute     "&#xCD;">
<!ENTITY iacute     "&#xED;">
<!ENTITY Icirc      "&#xCE;">
<!ENTITY icirc      "&#xEE;">
<!ENTITY Igrave     "&#xCC;">
<!ENTITY igrave     "&#xEC;">
<!ENTITY isin       "&#x2208;">
<!ENTITY Iuml       "&#xCF;">
<!ENTITY iuml       "&#xEF;">
<!ENTITY lArr       "&#x21D0;">
<!ENTITY larr       "&#x2190;">
<!ENTITY ldquo      "&#x201C;">
<!ENTITY le         "&#x2264;">
<!ENTITY lfloor     "&#x230A;">
<!ENTITY mdash      "&#x2014;">
<!ENTITY micro      "&#xB5;">
<!ENTITY middot     "&#xB7;">
<!ENTITY mu     	"&#x03BC;">
<!ENTITY Nacute     "&#x8f;">
<!ENTITY nacute     "&#x90;">
<!ENTITY nbsp       "&#xA0;">
<!ENTITY ndash      "&#x2013;">
<!ENTITY ne         "&#x2260;">
<!ENTITY ni         "&#x220B;">
<!ENTITY notin      "&#x2209;">
<!ENTITY nsub       "&#x2284;">
<!ENTITY Ntilde     "&#xD1;">
<!ENTITY ntilde     "&#xF1;">
<!ENTITY Oacute     "&#xD3;">
<!ENTITY oacute     "&#xF3;">
<!ENTITY Ocirc      "&#xD4;">
<!ENTITY ocirc      "&#xF4;">
<!ENTITY Omicron    "&#x39F;">   <!-- Better use &#x1d4aa; for big-O notation ('MATHEMATICAL SCRIPT CAPITAL O') -->
<!ENTITY Otilde     "&#xD5;">
<!ENTITY otilde     "&#xF5;">
<!ENTITY Ouml       "&#xD6;">
<!ENTITY ouml       "&#xF6;">
<!ENTITY para       "&#xB6;">
<!ENTITY phi        "&#x3C6;">
<!ENTITY pi         "&#x3C0;">
<!ENTITY plusmn     "&#xB1;">
<!ENTITY rArr       "&#x21D2;">
<!ENTITY rarr       "&#x2192;">
<!ENTITY rdquo      "&#x201D;">
<!ENTITY rfloor     "&#x230B;">
<!ENTITY rho        "&#x3C1;">
<!ENTITY rsquo      "&#x2019;">
<!ENTITY Scaron     "&#x160;">
<!ENTITY scaron     "&#x161;">
<!ENTITY sect       "&#xA7;">
<!ENTITY sigma      "&#x3C3;">
<!ENTITY sub        "&#x2282;">
<!ENTITY sube       "&#x2286;">
<!ENTITY sum        "&#x2211;">
<!ENTITY sup        "&#x2283;">
<!ENTITY supe       "&#x2287;">
<!ENTITY szlig      "&#xDF;">
<!ENTITY Theta      "&#x398;">
<!ENTITY times      "&#xD7;">
<!ENTITY Uacute     "&#xDA;">
<!ENTITY uacute     "&#xFA;">
<!ENTITY Ucirc      "&#xDB;">
<!ENTITY ucirc      "&#xFB;">
<!ENTITY Ugrave     "&#xD9;">
<!ENTITY ugrave     "&#xF9;">
<!ENTITY Uuml       "&#xDC;">
<!ENTITY uuml       "&#xFC;">
<!ENTITY yacute     "&#xFD;">
<!ENTITY yuml       "&#xFF;">
<!ENTITY zcaron     "&#x17D;">

=== timsong-cpp/LWG/xml/issue2857.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="2857" status="Immediate">
<title><tt>{variant,optional,any}::emplace</tt> should return the constructed value</title>
<section><sref ref="[optional]"/><sref ref="[variant]"/><sref ref="[any]"/></section>
<submitter>Zhihao Yuan</submitter>
<date>25 Jan 2017</date>
<priority>1</priority>

<discussion>
<p>
When you want to continue operate on the new contained object constructed by <tt>emplace</tt>, you probably 
don't want to go through the type-safe machinery again.
</p>

<note>2017-01-27 Telecon</note>
<p>Priority 1; send to LEWG.</p>

<note>Kona 2017-03-02</note>
<p>Accepted as Immediate because P1.</p>
</discussion>

<resolution>
<p>This wording is relative to <a href="http://wg21.link/n4618">N4618</a>.</p>

<ol>
<li><p>Update the following signatures in <sref ref="[optional.optional]"/>, class template <tt>optional</tt> synopsis, 
as indicated:</p>

<blockquote>
<pre>
[&hellip;]
<i>// <sref ref="[optional.assign]"/>, assignment</i>
[&hellip;]
template &lt;class... Args&gt; <del>void</del><ins>T&amp;</ins> emplace(Args&amp;&amp;...);
template &lt;class U, class... Args&gt;
  <del>void</del><ins>T&amp;</ins> emplace(initializer_list&lt;U&gt;, Args&amp;&amp;...);
[&hellip;]
</pre>
</blockquote>
</li>

<li><p>Modify <sref ref="[optional.assign]"/> as indicated:</p>
<blockquote>
<pre>
template &lt;class... Args&gt; <del>void</del><ins>T&amp;</ins> emplace(Args&amp;&amp;... args);
</pre>
<blockquote>
<p>
[&hellip;]
<p/>
-27- <i>Postconditions:</i> <tt>*this</tt> contains a value.
<p/>
<ins>-?- <i>Returns:</i> A reference to the new contained value.</ins>
<p/>
-28- <i>Throws:</i> Any exception thrown by the selected constructor of <tt>T</tt>.
</p>
</blockquote>
<pre>
template &lt;class U, class... Args&gt; <del>void</del><ins>T&amp;</ins> emplace(initializer_list&lt;U&gt; il, Args&amp;&amp;... args);
</pre>
<blockquote>
<p>
[&hellip;]
<p/>
-31- <i>Postconditions:</i> <tt>*this</tt> contains a value.
<p/>
<ins>-?- <i>Returns:</i> A reference to the new contained value.</ins>
<p/>
-32- <i>Throws:</i> Any exception thrown by the selected constructor of <tt>T</tt>.
</p>
</blockquote>
</blockquote>
</li>

<li><p>Modify the following signatures in <sref ref="[variant.variant]"/>, class template <tt>variant</tt> synopsis, as indicated:</p>

<blockquote>
<pre>
[&hellip;]
<i>// <sref ref="[variant.mod]"/>, modifiers</i>
template &lt;class T, class... Args&gt; <del>void</del><ins>T&amp;</ins> emplace(Args&amp;&amp;...);
template &lt;class T, class U, class... Args&gt;
  <del>void</del><ins>T&amp;</ins> emplace(initializer_list&lt;U&gt;, Args&amp;&amp;...);
template &lt;size_t I, class... Args&gt; <del>void</del><ins>variant_alternative_t&lt;I, variant&lt;Types...&gt;&gt;&amp;</ins> emplace(Args&amp;&amp;...);
template &lt;size_t I, class U, class... Args&gt;
  <del>void</del><ins>variant_alternative_t&lt;I, variant&lt;Types...&gt;&gt;&amp;</ins> emplace(initializer_list&lt;U&gt;, Args&amp;&amp;...);
[&hellip;]
</pre>
</blockquote>
</li>

<li><p>Modify <sref ref="[variant.mod]"/> as indicated:</p>

<blockquote>
<pre>
template &lt;class T, class... Args&gt; <del>void</del><ins>T&amp;</ins> emplace(Args&amp;&amp;... args);
</pre>
<blockquote>
<p>
-1- <i>Effects:</i> Equivalent to <tt><ins>return</ins> emplace&lt;<i>I</i>&gt;(std::forward&lt;Args&gt;(args)...)<ins>;</ins></tt> 
where <tt><i>I</i></tt> is the zero-based index of <tt>T</tt> in <tt>Types...</tt>.
<p/>
[&hellip;]
</p>
</blockquote>

<pre>
template &lt;class T, class U, class... Args&gt;
  <del>void</del><ins>T&amp;</ins> emplace(initializer_list&lt;U&gt; il, Args&amp;&amp;... args);
</pre>
<blockquote>
<p>
-3- <i>Effects:</i> Equivalent to <tt><ins>return</ins> emplace&lt;<i>I</i>&gt;(il, std::forward&lt;Args&gt;(args)...)<ins>;</ins></tt> 
where <tt><i>I</i></tt> is the zero-based index of <tt>T</tt> in <tt>Types...</tt>.
<p/>
[&hellip;]
</p>
</blockquote>

<pre>
template &lt;size_t I, class... Args&gt; <del>void</del><ins>variant_alternative_t&lt;I, variant&lt;Types...&gt;&gt;&amp;</ins> emplace(Args&amp;&amp;... args);
</pre>
<blockquote>
<p>
[&hellip;]
<p/>
-7- <i>Postconditions:</i> <tt>index()</tt> is <tt>I</tt>.
<p/>
<ins>-?- <i>Returns:</i> A reference to the new contained value.</ins>
<p/>
-8- <i>Throws:</i> Any exception thrown during the initialization of the contained value.
<p/>
[&hellip;]
</p>
</blockquote>

<pre>
template &lt;size_t I, class U, class... Args&gt;
  <del>void</del><ins>variant_alternative_t&lt;I, variant&lt;Types...&gt;&gt;&amp;</ins> emplace(initializer_list&lt;U&gt; il, Args&amp;&amp;... args);
</pre>
<blockquote>
<p>
[&hellip;]
<p/>
-12- <i>Postconditions:</i> <tt>index()</tt> is <tt>I</tt>.
<p/>
<ins>-?- <i>Returns:</i> A reference to the new contained value.</ins>
<p/>
-13- <i>Throws:</i> Any exception thrown during the initialization of the contained value.
<p/>
[&hellip;]
</p>
</blockquote>
</blockquote>
</li>

<li><p>Modify the following signatures in <sref ref="[any.class]"/>, class <tt>any</tt> synopsis, as indicated:</p>
<blockquote>
<pre>
[&hellip;]
<i>// <sref ref="[any.modifiers]"/>, modifiers</i>
template &lt;class ValueType, class... Args&gt;
  <del>void</del><ins>decay_t&lt;ValueType&gt;&amp;</ins> emplace(Args&amp;&amp; ...);
template &lt;class ValueType, class U, class... Args&gt;
  <del>void</del><ins>decay_t&lt;ValueType&gt;&amp;</ins> emplace(initializer_list&lt;U&gt;, Args&amp;&amp;...);
[&hellip;]
</pre>
</blockquote>
</li>

<li><p>Modify <sref ref="[any.modifiers]"/> as indicated:</p>
<blockquote>
<pre>
template &lt;class ValueType, class... Args&gt;
  <del>void</del><ins>decay_t&lt;ValueType&gt;&amp;</ins> emplace(Args&amp;&amp;... args);
</pre>
<blockquote>
<p>
[&hellip;]
<p/>
-4- <i>Postconditions:</i> <tt>*this</tt> contains a value.
<p/>
<ins>-?- <i>Returns:</i> A reference to the new contained value.</ins>
<p/>
-5- <i>Throws:</i> Any exception thrown by the selected constructor of <tt>T</tt>.
<p/>
[&hellip;]
</p>
</blockquote>

<pre>
template &lt;class ValueType, class U, class... Args&gt;
  <del>void</del><ins>decay_t&lt;ValueType&gt;&amp;</ins> emplace(initializer_list&lt;U&gt; il, Args&amp;&amp;... args);
</pre>
<blockquote>
<p>
[&hellip;]
<p/>
-10- <i>Postconditions:</i> <tt>*this</tt> contains a value.
<p/>
<ins>-?- <i>Returns:</i> A reference to the new contained value.</ins>
<p/>
-11- <i>Throws:</i> Any exception thrown by the selected constructor of <tt>T</tt>.
<p/>
[&hellip;]
</p>
</blockquote>
</blockquote>
</li>

</ol>
</resolution>

</issue>

=== timsong-cpp/LWG/xml/issue3161.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3161" status="Open">
<title>Container adapters mandate use of <tt>emplace_back</tt> but don't require it</title>
<section><sref ref="[stack]"/> <sref ref="[queue]"/></section>
<submitter>Marshall Clow</submitter>
<date>2 Oct 2018</date>
<priority>99</priority>

<discussion>
<p>
<sref ref="[stack]"/> p1 says:
</p>
<blockquote>
Any sequence container supporting operations <tt>back()</tt>, <tt>push_back()</tt> and <tt>pop_back()</tt> can be used to 
instantiate <tt>stack</tt>. 
</blockquote>

<p>but then in <sref ref="[stack.defn]"/> we have the following code:</p>
<pre>
template&lt;class... Args&gt;
  decltype(auto) emplace(Args&amp;&amp;... args)
    { return c.emplace_back(std::forward&lt;Args&gt;(args)...); }
</pre>

<p>The same pattern appears in <sref ref="[queue]"/>.</p>

<p>I see two ways to resolve this:</p>
<p>The first is to add <tt>emplace_back()</tt> to the list of requirements for underlying containers for <tt>stack</tt> and <tt>queue</tt></p>

<p>The second is to replace the calls to <tt>c.emplace_back(std::forward&lt;Args&gt;(args)...)</tt> with <tt>c.emplace(c.end(), std::forward&lt;Args&gt;(args)...)</tt>. We can do this w/o messing with the list above because <tt>emplace</tt> is part of the sequence container requirements, while <tt>emplace_back</tt> is not. I checked the libc++ implementation of <tt>vector</tt>, <tt>deque</tt>, and <tt>list</tt>, and they all do the same thing for <tt>emplace(end(), ...)</tt> and <tt>emplace_back(...)</tt>.</p>

<note>2019-02; Kona Wednesday night issue processing</note>
<p>Status to Open; Casey to provide updated wording, and re-vote on reflector.</p>
<p>Polls were: NAD - 5-1-3; "Option B" - 2-5-2 and "Probe the container" - 7-2-0</p>
</discussion>

<resolution>
<p>This wording is relative to <a href="https://wg21.link/n4762">N4762</a>.</p>

<blockquote class="note">
I have prepared two mutually exclusive options.
<br/>Option A a requirement for <tt>emplace_back</tt> to the underlying container.
<br/>Option B one replaces the calls to <tt>emplace_back</tt> with calls to <tt>emplace</tt>.
</blockquote>

<p><b>Option A</b></p>
<ol>
<li><p>Edit <sref ref="[stack]"/>, as indicated:</p>
<p>Any sequence container supporting operations <tt>back()</tt>, <tt>push_back()</tt>,  <ins><tt>emplace_back()</tt></ins> and <tt>pop_back()</tt> can be used to instantiate <tt>stack</tt>. </p>
</li>

<li><p>Edit <sref ref="[queue.defn]"/>, as indicated:</p>
<p>Any sequence container supporting operations <tt>front()</tt>, <tt>back()</tt>, <tt>push_back()</tt>,  <ins><tt>emplace_back()</tt></ins> and <tt>pop_front()</tt> can be used to instantiate <tt>queue</tt>. </p>
</li>
</ol>

<p><b>Option B</b></p>
<ol>
<li><p>Edit <sref ref="[stack.defn]"/>, class template <tt>stack</tt> definition, as indicated:</p>
<blockquote><pre>
template&lt;class... Args&gt;
  decltype(auto) emplace(Args&amp;&amp;... args)
    { return c.emplace<del>_back</del>(<ins>c.end(), </ins>std::forward&lt;Args&gt;(args)...); }
</pre></blockquote>
</li>

<li><p>Edit <sref ref="[queue.defn]"/>, class template <tt>queue</tt> definition, as indicated:</p>
<blockquote><pre>
template&lt;class... Args&gt;
  decltype(auto) emplace(Args&amp;&amp;... args)
    { return c.emplace<del>_back</del>(<ins>c.end(), </ins>std::forward&lt;Args&gt;(args)...); }
</pre></blockquote>
</li>
</ol>

</resolution>

</issue>

=== timsong-cpp/LWG/xml/issue2804.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="2804" status="Pending WP">
<title>Unconditional <tt>constexpr</tt> default constructor for <tt>istream_iterator</tt></title>
<section><sref ref="[istream.iterator.cons]"/></section>
<submitter>United States</submitter>
<date>9 Nov 2016</date>
<priority>0</priority>

<discussion>
<p>
<b>Addresses US 152</b>
<p/>
<i>see below</i> for the default constructor should simply be 
spelled <tt>constexpr</tt>. The current declaration looks like a 
member function, not a constructor, and the <tt>constexpr</tt> 
keyword implicitly does not apply unless the instantiation could 
make it so, under the guarantees al ready present in the Effects clause.
</p>
<p>
Proposed change:
<p/>
Replace <i>see below</i> with <tt>constexpr</tt> in the declaration 
of the default constructor for <tt>istream_iterator</tt> in the 
class definition, and function specification.
</p>

<note>Issues Telecon 16-Dec-2016</note>
<p>Jonathan provides wording, Move to Tentatively Ready</p>
</discussion>

<resolution>
<p>In the class synopsis in 24.6.1 [istream.iterator] change the default constructor:</p>
<blockquote>
<pre>
<del><i>see below</i></del><ins>constexpr</ins> istream_iterator();
istream_iterator(istream_type&amp; s);
istream_iterator(const istream_iterator&amp; x) = default;
~istream_iterator() = default;
</pre>
</blockquote>

<p>Change [istream.iterator.cons] before paragraph 1:</p>
<blockquote>
<pre>
<del><i>see below</i></del><ins>constexpr</ins> istream_iterator();

-1- Effects: ...
</pre>
</blockquote>
</resolution>

</issue>

=== timsong-cpp/LWG/xml/issue2482.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="2482" status="C++17">
<title>&sect;[c.strings] Table 73 mentions nonexistent functions</title>
<section><sref ref="[c.strings]"/></section>
<submitter>S. B.Tam</submitter>
<date>18 Jan 2015</date>
<priority>99</priority>

<discussion>
<p>
N4296 Table 73 mentions the functions <tt>mbsrtowc</tt> and <tt>wcsrtomb</tt>, which are not defined in ISO C 
or ISO C++. Presumably they should be <tt>mbsrtowcs</tt> and <tt>wcsrtombs</tt> instead. 
</p>

<note>2015-04-02 Library reflector vote</note>
<p>
The issue has been identified as Tentatively Ready based on six votes in favour.
</p>
</discussion>

<resolution>

<p>This wording is relative to N4296.</p>

<ol>
<li>
<blockquote>
<table border="1" cellpadding="4" rules="groups" style="table-layout:fixed">
<caption>Table 33 &mdash; Potential <tt>mbstate_t</tt> data races</caption>
<tr>
<td>
<tt>mbrlen</tt>
</td>
<td>
<tt>mbrtowc</tt>
</td>
<td>
<tt>mbsrtowc<ins>s</ins></tt>
</td>
<td>
<tt>mbtowc</tt>
</td>
<td>
<tt>wcrtomb</tt>
</td>
</tr>

<tr>
<td>
<tt>wcsrtomb<ins>s</ins></tt>
</td>
<td>
<tt>wctomb</tt>
</td>
</tr>

</table>
</blockquote>
</li>
</ol>

</resolution>

</issue>
