=== timsong-cpp/LWG/xml/lwg-issue.dtd
<!ELEMENT issue (title,section,submitter,date,priority?,(note,p*)?,discussion,(resolution|rationale|duplicate|note|blockquote)*)>
<!ATTLIST issue num CDATA #REQUIRED>
<!ATTLIST issue status CDATA #REQUIRED>
<!ELEMENT title ANY>
<!ELEMENT section (sref+)>
<!ELEMENT submitter (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT priority (#PCDATA)>
<!ELEMENT discussion ANY>
<!ELEMENT resolution ANY>
<!ELEMENT rationale ANY>
<!ELEMENT duplicate (iref)>
<!ELEMENT sref EMPTY>
<!ATTLIST sref ref CDATA #REQUIRED>
<!ELEMENT iref EMPTY>
<!ATTLIST iref ref CDATA #REQUIRED>
<!ELEMENT note ANY>

<!ENTITY % html-inline "tt|code|i|em|b|strong|u|a|sup|sub|br|var|span|dfn|del|ins">
<!ENTITY % html-table "table|thead|tbody|caption|tr|th|td">
<!ENTITY % html-list "ol|ul|li|dl|dt|dd">
<!ENTITY % html-block "p|pre|blockquote|h3|h4|h5|%html-table;|%html-list;">
<!ENTITY % html "%html-inline; | %html-block;">

<!-- HTML elements used in issues -->
<!ELEMENT del ANY>
<!ELEMENT ins ANY>
<!ATTLIST ins style CDATA #IMPLIED>
<!ELEMENT pre ANY>
<!ELEMENT blockquote ANY>
<!ATTLIST blockquote class (note) #IMPLIED> <!-- issue 427 needs this -->
<!ATTLIST blockquote style CDATA #IMPLIED>
<!ELEMENT p ANY>
<!ATTLIST p style CDATA #IMPLIED>
<!ELEMENT h3 ANY>
<!ELEMENT h4 ANY>
<!ELEMENT h5 ANY>
<!ELEMENT ol (li+)>
<!ATTLIST ol style CDATA #IMPLIED>
<!ATTLIST ol start CDATA #IMPLIED>
<!ELEMENT ul (li+)>
<!ELEMENT li ANY>
<!ATTLIST li value CDATA #IMPLIED>
<!ELEMENT i ANY>
<!ELEMENT em ANY>
<!ELEMENT b ANY>
<!ELEMENT strong ANY>
<!ELEMENT u ANY>
<!ELEMENT tt ANY>
<!ELEMENT code ANY>
<!ELEMENT sup ANY>
<!ELEMENT sub ANY>
<!ELEMENT br ANY>
<!ELEMENT a ANY>
<!ATTLIST a href CDATA #IMPLIED>
<!ATTLIST a name CDATA #IMPLIED>
<!ELEMENT table (caption?,((thead?,tbody)|tr+))>
<!ATTLIST table style CDATA #IMPLIED>
<!ATTLIST table border CDATA #IMPLIED>
<!ATTLIST table bordercolor CDATA #IMPLIED>
<!ATTLIST table cellpadding CDATA #IMPLIED>
<!ATTLIST table cellspacing CDATA #IMPLIED>
<!ATTLIST table rules CDATA #IMPLIED>
<!ELEMENT thead ANY>
<!ELEMENT tbody ANY>
<!ELEMENT tr ((th|td)+)>
<!ATTLIST tr style CDATA #IMPLIED>
<!ATTLIST tr align CDATA #IMPLIED>
<!ELEMENT th ANY>
<!ATTLIST th style CDATA #IMPLIED>
<!ATTLIST th colspan CDATA #IMPLIED>
<!ATTLIST th align CDATA #IMPLIED>
<!ELEMENT td ANY>
<!ATTLIST td style CDATA #IMPLIED>
<!ATTLIST td colspan CDATA #IMPLIED>
<!ATTLIST td rowspan CDATA #IMPLIED>
<!ATTLIST td align CDATA #IMPLIED>
<!ATTLIST td valign CDATA #IMPLIED>
<!ELEMENT caption ANY>
<!ELEMENT dl ((dd|dt)+)>
<!ELEMENT dt ANY>
<!ELEMENT dd ANY>
<!ELEMENT var ANY>
<!ELEMENT span ANY>
<!ATTLIST span style CDATA #IMPLIED>
<!ELEMENT dfn ANY>

<!-- MathML elements, simplified DTD version derived from:

     https://www.w3.org/TR/MathML2/appendixa.html
     
     To convert LaTeX to MathML, use e.g.:
     
     https://www.mathtowebonline.com/
     
     Useful MathML introductions:
     
     http://www.xmlmind.com/tutorials/MathML/
     http://rypress.com/tutorials/mathml/advanced-formatting
-->
<!ENTITY % MathMLCharacters "#PCDATA | mglyph">
<!ENTITY % MathExpression           
     "(mi|mn|mo|mtext|ms|mspace|mrow|mfrac|msqrt|mroot|menclose|mstyle|mfenced|
       mtable)*">
<!ENTITY % PresExpression      
     "(mfenced|mi|mo|mn|msup|mtext|ms|mspace|mprescripts|mfrac|msqrt|mroot|mrow|mstyle|
       msub|msup|msubsup|munder|mover|munderover|mmultiscripts|mtable|mtr|mlabeledtr|
       mtd)*">
<!ENTITY % MATHML.NamespaceDecl.attrib "xmlns CDATA #REQUIRED">
<!ENTITY % MATHML.Common.attrib
     "class  CDATA  #IMPLIED
      style  CDATA  #IMPLIED
      id     ID     #IMPLIED
      xref   IDREF  #IMPLIED
      other  CDATA  #IMPLIED">
<!ENTITY % att-bevelled        "bevelled CDATA #IMPLIED">
<!ENTITY % att-display         "display CDATA #IMPLIED">
<!ENTITY % att-numalign        "numalign CDATA #IMPLIED">
<!ENTITY % att-denomalign      "denomalign CDATA #IMPLIED">
<!ENTITY % att-linethickness   "linethickness CDATA #IMPLIED">
<!ENTITY % att-fontsize        "fontsize CDATA #IMPLIED">
<!ENTITY % att-fontweight      "fontweight (normal|bold) #IMPLIED">
<!ENTITY % att-fontstyle       "fontstyle (normal|italic) #IMPLIED">
<!ENTITY % att-fontfamily      "fontfamily CDATA #IMPLIED">
<!ENTITY % att-color           "color CDATA #IMPLIED">
<!ENTITY % att-mathvariant     "mathvariant CDATA #IMPLIED">
<!ENTITY % att-mathsize        "mathsize CDATA #IMPLIED">
<!ENTITY % att-mathcolor       "mathcolor CDATA #IMPLIED">
<!ENTITY % att-mathbackground  "mathbackground CDATA #IMPLIED">
<!ENTITY % att-mode            "mode CDATA #IMPLIED">
<!ENTITY % att-fontinfo        "%att-fontsize; %att-fontweight; %att-fontstyle;
                                %att-fontfamily; %att-color; %att-mathvariant;
                                %att-mathsize; %att-mathcolor; %att-mathbackground;">
<!ENTITY % att-form            "form  (prefix|infix|postfix ) #IMPLIED">
<!ENTITY % att-fence           "fence  (true|false) #IMPLIED">
<!ENTITY % att-separator       "separator (true|false) #IMPLIED">
<!ENTITY % att-lspace          "lspace CDATA #IMPLIED">
<!ENTITY % att-rspace          "rspace CDATA #IMPLIED">
<!ENTITY % att-stretchy        "stretchy (true|false) #IMPLIED">
<!ENTITY % att-symmetric       "symmetric (true|false) #IMPLIED">
<!ENTITY % att-maxsize         "maxsize CDATA #IMPLIED">
<!ENTITY % att-minsize         "minsize CDATA #IMPLIED">
<!ENTITY % att-largeop         "largeop (true|false) #IMPLIED">
<!ENTITY % att-movablelimits   "movablelimits (true|false) #IMPLIED">
<!ENTITY % att-accent          "accent (true|false) #IMPLIED">
<!ENTITY % att-opinfo          "%att-form; %att-fence; %att-separator; %att-lspace; %att-rspace;
                                %att-stretchy; %att-symmetric; %att-maxsize; %att-minsize;
                                %att-largeop; %att-movablelimits; %att-accent;">
<!ENTITY % att-lquote          "lquote CDATA #IMPLIED">
<!ENTITY % att-rquote          "rquote CDATA #IMPLIED">
<!ENTITY % att-linethickness   "linethickness CDATA #IMPLIED">
<!ENTITY % att-scriptlevel     "scriptlevel CDATA #IMPLIED">
<!ENTITY % att-displaystyle    "displaystyle (true|false) #IMPLIED">
<!ENTITY % att-scriptsizemultiplier "scriptsizemultiplier CDATA #IMPLIED">
<!ENTITY % att-scriptminsize   "scriptminsize CDATA #IMPLIED">
<!ENTITY % att-background      "background CDATA #IMPLIED">
<!ENTITY % att-open            "open CDATA #IMPLIED">
<!ENTITY % att-close           "close CDATA #IMPLIED">
<!ENTITY % att-separators      "separators CDATA #IMPLIED">
<!ENTITY % att-subscriptshift  "subscriptshift CDATA #IMPLIED">
<!ENTITY % att-superscriptshift "superscriptshift CDATA #IMPLIED">
<!ENTITY % att-accentunder     "accentunder (true|false) #IMPLIED">
<!ENTITY % att-align           "align CDATA #IMPLIED">
<!ENTITY % att-rowspan         "rowspan CDATA #IMPLIED">
<!ENTITY % att-columnspan      "columnspan CDATA #IMPLIED">
<!ENTITY % att-edge            "edge (left|right) #IMPLIED">
                             
<!ENTITY % twoPresExpression   "%PresExpression;">
<!ENTITY % threePresExpression "%PresExpression;">
<!ENTITY % prscrPresExpression "%PresExpression;">

<!ELEMENT math          (%MathExpression;)>
<!ELEMENT malignmark    EMPTY>
<!ELEMENT mglyph        EMPTY>
<!ELEMENT mrow          (%PresExpression;)>
<!ELEMENT mi            (%MathMLCharacters; | malignmark)*>
<!ELEMENT mn            (%MathMLCharacters; | malignmark)*>
<!ELEMENT mo            (%MathMLCharacters; | malignmark)*>
<!ELEMENT mtext         (%MathMLCharacters; | malignmark)*>
<!ELEMENT ms            (%MathMLCharacters; | malignmark)*>
<!ELEMENT mfenced       (%PresExpression;)>
<!ELEMENT mroot         (%twoPresExpression;)>
<!ELEMENT msub          (%twoPresExpression;)>
<!ELEMENT msup          (%twoPresExpression;)>
<!ELEMENT msubsup       (%threePresExpression;)>
<!ELEMENT mmultiscripts (%prscrPresExpression;)>
<!ELEMENT munder        (%twoPresExpression;)>
<!ELEMENT munderover    (%threePresExpression;)>
<!ELEMENT mover         (%twoPresExpression;)>
<!ELEMENT mfrac         (%twoPresExpression;)>
<!ELEMENT msqrt         (%PresExpression;)>
<!ELEMENT mstyle        (%PresExpression;)>

<!ATTLIST math          %att-mode; %att-display; %MATHML.NamespaceDecl.attrib;>
<!ATTLIST mglyph        %att-alt; %att-fontfamily; %att-index;>
<!ATTLIST mrow          %MATHML.Common.attrib;>
<!ATTLIST mi            %MATHML.Common.attrib; %att-fontinfo;>
<!ATTLIST mo            %MATHML.Common.attrib; %att-fontinfo; %att-opinfo;>
<!ATTLIST mn            %MATHML.Common.attrib; %att-fontinfo;>
<!ATTLIST mtext         %MATHML.Common.attrib; %att-fontinfo;>
<!ATTLIST ms            %MATHML.Common.attrib; %att-fontinfo; %att-lquote; %att-rquote;>
<!ATTLIST mfenced       %MATHML.Common.attrib; %att-open; %att-close; %att-separators;>
<!ATTLIST mfrac         %MATHML.Common.attrib; %att-bevelled; %att-numalign; %att-denomalign; %att-linethickness;>
<!ATTLIST msqrt         %MATHML.Common.attrib;>
<!ATTLIST mroot         %MATHML.Common.attrib;>
<!ATTLIST msub          %MATHML.Common.attrib; %att-subscriptshift;>
<!ATTLIST msup          %MATHML.Common.attrib; %att-superscriptshift;>
<!ATTLIST msubsup       %MATHML.Common.attrib; %att-subscriptshift; %att-superscriptshift;>
<!ATTLIST munder        %MATHML.Common.attrib; %att-accentunder;>
<!ATTLIST mover         %MATHML.Common.attrib; %att-accent;>
<!ATTLIST munderover    %MATHML.Common.attrib; %att-accent; %att-accentunder;>
<!ATTLIST mmultiscripts %MATHML.Common.attrib; %att-subscriptshift; %att-superscriptshift;>
<!ATTLIST mstyle        %MATHML.Common.attrib; %att-fontinfo; %att-opinfo; %att-lquote;
                        %att-rquote; %att-linethickness; %att-scriptlevel; %att-scriptsizemultiplier;
                        %att-scriptminsize; %att-background; %att-open; %att-close;
                        %att-separators; %att-subscriptshift; %att-superscriptshift;
                        %att-accentunder; %att-tableinfo; %att-rowspan; %att-columnspan;
                        %att-edge; %att-selection; %att-bevelled; %att-height; %att-depth;>

<!-- the common HTML entities for special characters -->
<!ENTITY Aacute     "&#xC1;">
<!ENTITY aacute     "&#xE1;">
<!ENTITY Acirc      "&#xC2;">
<!ENTITY acirc      "&#xE2;">
<!ENTITY Agrave     "&#xC0;">
<!ENTITY agrave     "&#xE0;">
<!ENTITY Atilde     "&#xC3;">
<!ENTITY atilde     "&#xE3;">
<!ENTITY Auml       "&#xC4;">
<!ENTITY auml       "&#xE4;">
<!ENTITY Ccedil     "&#xC7;">
<!ENTITY ccedil     "&#xE7;">
<!ENTITY deg        "&#xB0;">
<!ENTITY Delta      "&#x394;">
<!ENTITY delta      "&#x3B4;">
<!ENTITY divide     "&#xF7;">
<!ENTITY Eacute     "&#xC9;">
<!ENTITY eacute     "&#xE9;">
<!ENTITY Ecirc      "&#xCA;">
<!ENTITY ecirc      "&#xEA;">
<!ENTITY Egrave     "&#xC8;">
<!ENTITY egrave     "&#xE8;">
<!ENTITY empty      "&#x2205;">
<!ENTITY epsilon    "&#x3B5;">
<!ENTITY Euml       "&#xCB;">
<!ENTITY euml       "&#xEB;">
<!ENTITY exist      "&#x2203;">
<!ENTITY forall     "&#x2200;">
<!ENTITY frasl      "&#x2044;">
<!ENTITY ge         "&#x2265;">
<!ENTITY hArr       "&#x21D4;">
<!ENTITY harr       "&#x2194;">
<!ENTITY hellip     "&#x2026;">
<!ENTITY Iacute     "&#xCD;">
<!ENTITY iacute     "&#xED;">
<!ENTITY Icirc      "&#xCE;">
<!ENTITY icirc      "&#xEE;">
<!ENTITY Igrave     "&#xCC;">
<!ENTITY igrave     "&#xEC;">
<!ENTITY isin       "&#x2208;">
<!ENTITY Iuml       "&#xCF;">
<!ENTITY iuml       "&#xEF;">
<!ENTITY lArr       "&#x21D0;">
<!ENTITY larr       "&#x2190;">
<!ENTITY ldquo      "&#x201C;">
<!ENTITY le         "&#x2264;">
<!ENTITY lfloor     "&#x230A;">
<!ENTITY mdash      "&#x2014;">
<!ENTITY micro      "&#xB5;">
<!ENTITY middot     "&#xB7;">
<!ENTITY mu     	"&#x03BC;">
<!ENTITY Nacute     "&#x8f;">
<!ENTITY nacute     "&#x90;">
<!ENTITY nbsp       "&#xA0;">
<!ENTITY ndash      "&#x2013;">
<!ENTITY ne         "&#x2260;">
<!ENTITY ni         "&#x220B;">
<!ENTITY notin      "&#x2209;">
<!ENTITY nsub       "&#x2284;">
<!ENTITY Ntilde     "&#xD1;">
<!ENTITY ntilde     "&#xF1;">
<!ENTITY Oacute     "&#xD3;">
<!ENTITY oacute     "&#xF3;">
<!ENTITY Ocirc      "&#xD4;">
<!ENTITY ocirc      "&#xF4;">
<!ENTITY Omicron    "&#x39F;">   <!-- Better use &#x1d4aa; for big-O notation ('MATHEMATICAL SCRIPT CAPITAL O') -->
<!ENTITY Otilde     "&#xD5;">
<!ENTITY otilde     "&#xF5;">
<!ENTITY Ouml       "&#xD6;">
<!ENTITY ouml       "&#xF6;">
<!ENTITY para       "&#xB6;">
<!ENTITY phi        "&#x3C6;">
<!ENTITY pi         "&#x3C0;">
<!ENTITY plusmn     "&#xB1;">
<!ENTITY rArr       "&#x21D2;">
<!ENTITY rarr       "&#x2192;">
<!ENTITY rdquo      "&#x201D;">
<!ENTITY rfloor     "&#x230B;">
<!ENTITY rho        "&#x3C1;">
<!ENTITY rsquo      "&#x2019;">
<!ENTITY Scaron     "&#x160;">
<!ENTITY scaron     "&#x161;">
<!ENTITY sect       "&#xA7;">
<!ENTITY sigma      "&#x3C3;">
<!ENTITY sub        "&#x2282;">
<!ENTITY sube       "&#x2286;">
<!ENTITY sum        "&#x2211;">
<!ENTITY sup        "&#x2283;">
<!ENTITY supe       "&#x2287;">
<!ENTITY szlig      "&#xDF;">
<!ENTITY Theta      "&#x398;">
<!ENTITY times      "&#xD7;">
<!ENTITY Uacute     "&#xDA;">
<!ENTITY uacute     "&#xFA;">
<!ENTITY Ucirc      "&#xDB;">
<!ENTITY ucirc      "&#xFB;">
<!ENTITY Ugrave     "&#xD9;">
<!ENTITY ugrave     "&#xF9;">
<!ENTITY Uuml       "&#xDC;">
<!ENTITY uuml       "&#xFC;">
<!ENTITY yacute     "&#xFD;">
<!ENTITY yuml       "&#xFF;">
<!ENTITY zcaron     "&#x17D;">

=== timsong-cpp/LWG/xml/issue2812.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="2812" status="C++17">
<title>Range access is available with <tt>&lt;string_view&gt;</tt></title>
<section><sref ref="[iterator.range]"/><sref ref="[string.view.synop]"/></section>
<submitter>Johel Ernesto Guerrero Pe&ntilde;a</submitter>
<date>29 Oct 2016</date>
<priority>0</priority>

<discussion>
<p>
<sref ref="[string.view.synop]"/>/1 states
</p>
<blockquote><p>
The function templates defined in 20.2.2 and 24.7 are available when <tt>&lt;string_view&gt;</tt> is included.
</p></blockquote>
<p>
<sref ref="[iterator.range]"/>, in p1 is missing <tt>&lt;string_view&gt;</tt>.
</p>

<note>Issues Telecon 16-Dec-2016</note>
<p>Move to Tentatively Ready</p>
</discussion>

<resolution>
<p>This wording is relative to N4606.</p>

<ol>
<li>
<p>Edit <sref ref="[iterator.range]"/> p1 as indicated:</p>

<blockquote>
<p>
-1- In addition to being available via inclusion of the <tt>&lt;iterator&gt;</tt> header, the function templates 
in 24.7 are available when any of the following headers are included: <tt>&lt;array&gt;</tt>, <tt>&lt;deque&gt;</tt>, 
<tt>&lt;forward_list&gt;</tt>, <tt>&lt;list&gt;</tt>, <tt>&lt;map&gt;</tt>, <tt>&lt;regex&gt;</tt>, 
<tt>&lt;set&gt;</tt>, <tt>&lt;string&gt;</tt><ins>, <tt>&lt;string_view&gt;</tt></ins>, <tt>&lt;unordered_map&gt;</tt>, 
<tt>&lt;unordered_set&gt;</tt>, and <tt>&lt;vector&gt;</tt>.
</p>
</blockquote>
</li>
</ol>

</resolution>

</issue>

=== timsong-cpp/LWG/xml/issue3749.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>
<!DOCTYPE issue SYSTEM "lwg-issue.dtd">

<issue num="3749" status="WP">
<title><tt>common_iterator</tt> should handle integer-class difference types</title>
<section><sref ref="[iterators.common]"/></section>
<submitter>Hewill Kang</submitter>
<date>01 Aug 2022</date>
<priority>2</priority>

<discussion>
<p>
The partial specialization of <tt>iterator_traits</tt> for <tt>common_iterator</tt> is defined in 
<sref ref="[common.iterator]"/> as
</p>
<pre>
template&lt;input_iterator I, class S&gt;
struct iterator_traits&lt;common_iterator&lt;I, S&gt;&gt; {
  using iterator_concept = <i>see below</i>;
  using iterator_category = <i>see below</i>;
  using value_type = iter_value_t&lt;I&gt;;
  using difference_type = iter_difference_t&lt;I&gt;;
  using pointer = <i>see below</i>;
  using reference = iter_reference_t&lt;I&gt;;
};
</pre>
<p>
where <tt>difference_type</tt> is defined as <tt>iter_difference_t&lt;I&gt;</tt> and <tt>iterator_category</tt> 
is defined as at least <tt>input_iterator_tag</tt>. However, when <tt>difference_type</tt> is an 
integer-class type, <tt>common_iterator</tt> does not satisfy <i>Cpp17InputIterator</i>, which makes 
<tt>iterator_category</tt> incorrectly defined as <tt>input_iterator_tag</tt>.
</p>
<p>
Since the main purpose of <tt>common_iterator</tt> is to be compatible with the legacy iterator system, 
which is reflected in its efforts to try to provide the operations required by C++17 iterators even if 
the underlying iterator does not support it. We should handle this case of difference type incompatibility 
as well.
<p/>
The proposed solution is to provide a C++17 conforming difference type by clamping the integer-class type 
to <tt>ptrdiff_t</tt>.
<p/>
<b>Daniel:</b>
</p>
<blockquote class="note">
<p>
The second part of this issue provides an <em>alternative</em> resolution for the first part of 
LWG <iref ref="3748"/> and solves the casting problem mentioned in LWG <iref ref="3748"/> as well.
</p>
</blockquote>

<note>2022-08-23; Reflector poll</note>
<p>
Set priority to 2 after reflector poll.
</p>
<p>
"I think <code>common_iterator</code> should <em>reject</em> iterators with
integer-class difference types since it can't possibly achieve the design intent
of adapting them to <i>Cpp17Iterator</i>s."
</p>
<p>
"I'm not yet convinced that we need to outright reject such uses,
but I'm pretty sure that we shouldn't mess with the difference type
and that the PR is in the wrong direction."
</p>

<superseded>
<p>
This wording is relative to <paper num="N4910"/>.
</p>

<ol>
<li><p>Modify <sref ref="[common.iterator]"/> as indicated:</p>

<blockquote class="note">
<p>
[<i>Drafting note:</i> <tt>common_iterator</tt> requires iterator type <tt>I</tt> must model 
<tt>input_or_output_iterator</tt> which ensures that <tt>iter_difference_t&lt;I&gt;</tt> 
is a signed-integer-like type. The modification of <tt>common_iterator::operator-</tt> is to ensure 
that the pair of <tt>common_iterator&lt;I, S&gt;</tt> models <tt>sized_sentinel_for</tt> when 
<tt>sized_sentinel_for&lt;I, S&gt;</tt> is modeled for iterator type <tt>I</tt> with an 
integer-class difference type and its sentinel type <tt>S</tt>.]
</p>
</blockquote>

<blockquote>
<pre>
namespace std {
  <ins>template&lt;class D&gt;
    requires <i>is-signed-integer-like</i>&lt;D&gt;
  using <i>make-cpp17-diff-t</i> = conditional_t&lt;signed_integral&lt;D&gt;, D, ptrdiff_t&gt;;  <i>// exposition only</i></ins>

  template&lt;input_or_output_iterator I, sentinel_for&lt;I&gt; S>
    requires (!same_as&lt;I, S&gt; &amp;&amp; copyable&lt;I&gt;)
  class common_iterator {
  public:
    [&hellip;]
    template&lt;sized_sentinel_for&lt;I&gt; I2, sized_sentinel_for&lt;I&gt; S2>
      requires sized_sentinel_for&lt;S, I2&gt;
    friend constexpr <ins><i>make-cpp17-diff-t</i>&lt;</ins>iter_difference_t&lt;I2&gt;<ins>&gt;</ins> operator-(
      const common_iterator&amp; x, const common_iterator&lt;I2, S2&gt;&amp; y);
    [&hellip;]
  };
  
  template&lt;class I, class S&gt;
  struct incrementable_traits&lt;common_iterator&lt;I, S&gt;&gt; {
    using difference_type = <ins><i>make-cpp17-diff-t</i>&lt;</ins>iter_difference_t&lt;I&gt;<ins>&gt;</ins>;
  };

  template&lt;input_iterator I, class S&gt;
  struct iterator_traits&lt;common_iterator&lt;I, S&gt;&gt; {
    using iterator_concept = <i>see below</i>;
    using iterator_category = <i>see below</i>;
    using value_type = iter_value_t&lt;I&gt;;
    using difference_type = <ins><i>make-cpp17-diff-t</i>&lt;</ins>iter_difference_t&lt;I&gt;<ins>&gt;</ins>;
    using pointer = <i>see below</i>;
    using reference = iter_reference_t&lt;I&gt;;
  };
}
</pre>
</blockquote>
</li>

<li><p>Modify <sref ref="[common.iter.cmp]"/> as indicated:</p>

<blockquote class="note">
<p>
[<i>Drafting note:</i> If this issue is voted in at the same time as LWG <iref ref="3748"/>, the editor
is kindly informed that the changes indicated below supersede those of the before mentioned issues first 
part.]
</p>
</blockquote>

<blockquote>
<pre>
template&lt;sized_sentinel_for&lt;I&gt; I2, sized_sentinel_for&lt;I&gt; S2>
  requires sized_sentinel_for&lt;S, I2&gt;
friend constexpr <ins><i>make-cpp17-diff-t</i>&lt;</ins>iter_difference_t&lt;I2&gt;<ins>&gt;</ins> operator-(
  const common_iterator&amp; x, const common_iterator&lt;I2, S2&gt;&amp; y);
</pre>
<blockquote>
<p>
-5- <i>Preconditions</i>: <tt>x.v_.valueless_by_exception()</tt> and <tt>y.v_.valueless_by_exception()</tt> are 
each <tt>false</tt>.
<p/>
-6- <i>Returns</i>: <tt>0</tt> if <tt><i>i</i></tt> and <tt><i>j</i></tt> are each <tt>1</tt>, and 
otherwise <ins><tt>static_cast&lt;<i>make-cpp17-diff-t</i>&lt;iter_difference_t&lt;I2&gt;&gt;&gt;(</tt></ins><tt>get&lt;<i>i</i>&gt;(x.v_) 
- get&lt;<i>j</i>&gt;(y.v_)</tt><ins><tt>)</tt></ins>, where <tt><i>i</i></tt> is <tt>x.v_.index()</tt> 
and <tt><i>j</i></tt> is <tt>y.v_.index()</tt>.
</p>
</blockquote>
</blockquote>
</li>

</ol>
</superseded>

<note>2023-06-13; Varna; Tomasz provides wording</note>
<note>2023-06-14 Varna; Move to Ready</note>
<note>2023-11-11 Approved at November 2023 meeting in Kona. Status changed: Voting &rarr; WP.</note>
</discussion>

<resolution>
<p>
This wording is relative to <paper num="N4950"/>.
</p>

<ol>
<li><p>Modify <sref ref="[common.iterator]"/> as indicated:</p>

<blockquote>
<pre>
namespace std {
  [&hellip;]

  template&lt;input_iterator I, class S&gt;
  struct iterator_traits&lt;common_iterator&lt;I, S&gt;&gt; {
    using iterator_concept = <i>see below</i>;
    using iterator_category = <i>see below</i>; <ins>// <i>not always present</i></ins>
    using value_type = iter_value_t&lt;I&gt;;
    using difference_type = iter_difference_t&lt;I&gt;;
    using pointer = <i>see below</i>;
    using reference = iter_reference_t&lt;I&gt;;
  };
}
</pre>
</blockquote>
</li>

<li><p>Modify <sref ref="[common.iter.types]"/> as indicated:</p>

<blockquote>
<p>
<ins>-?- The nested <i>typedef-name</i> <tt>iterator_category</tt> of the specialization of <tt>iterator_traits</tt> for 
<tt>common_iterator&lt;I, S&gt;</tt> is defined if and only if <tt>iter_difference_t&lt;I&gt;</tt> is an integral type. 
In that case, <tt>iterator_category</tt> denotes <tt>forward_iterator_tag</tt> if the <i>qualified-id</i> 
<tt>iterator_traits&lt;I&gt;::iterator_category</tt> is valid and denotes a type that models 
<tt>derived_from&lt;forward_iterator_tag&gt;</tt>; otherwise it denotes <tt>input_iterator_tag</tt>.</ins>
</p>
<p>
-1- The <ins>remaining</ins> nested <i>typedef-name</i>s of the specialization of <tt>iterator_traits</tt> 
for <tt>common_iterator&lt;I, S&gt;</tt> are defined as follows<del>.</del><ins>:</ins>
</p>
<ol style="list-style-type: none">
<li><p>(1.1) &mdash; <tt>iterator_concept</tt> denotes <tt>forward_iterator_tag</tt> if <tt>I</tt> models 
<tt>forward_iterator</tt>; otherwise it denotes <tt>input_iterator_tag</tt>.</p></li>
<li><p><del>(1.2) &mdash; <tt>iterator_category</tt> denotes 
<tt>forward_iterator_tag</tt> if the <i>qualified-id</i> <tt>iterator_traits&lt;I&gt;::iterator_category</tt> is valid 
and denotes a type that models <tt>derived_from&lt;forward_iterator_tag&gt;</tt>; otherwise it denotes <tt>input_iterator_tag</tt>.</del></p></li>
<li><p>(1.3) &mdash; Let <tt>a</tt> denote an lvalue of type <tt>const common_iterator&lt;I, S&gt;</tt>. 
If the expression <tt>a.operator-&gt;()</tt> is well-formed, then <tt>pointer</tt> denotes <tt>decltype(a.operator->())</tt>. 
Otherwise, <tt>pointer</tt> denotes <tt>void</tt>.</p></li>
</ol>
</blockquote>
</li>

</ol>
</resolution>

</issue>
